# Scan res/meshes for .glb files and generate a mesh manifest header.
# Re-runs automatically when files are added/removed/modified.

file(GLOB_RECURSE MESH_FILES "${CMAKE_SOURCE_DIR}/res/meshes/*.glb")
list(SORT MESH_FILES)
list(LENGTH MESH_FILES MESH_COUNT)

# Build the enum
set(ENUM "// Auto-generated by CMake — do not edit\n")
string(APPEND ENUM "#pragma once\n\n")
string(APPEND ENUM "enum {\n")

# Build the filename table using designated initializers
set(TABLE "static const char *g_MeshFileNames[] = {\n")

foreach(f ${MESH_FILES})
  cmake_path(GET f FILENAME fname)

  # animal-beaver.glb → MESH_ANIMAL_BEAVER
  string(REGEX REPLACE "\\.glb$" "" base "${fname}")
  string(TOUPPER "${base}" upper)
  string(REGEX REPLACE "-" "_" symbol "${upper}")
  set(symbol "MESH_${symbol}")

  cmake_path(RELATIVE_PATH f BASE_DIRECTORY "${CMAKE_SOURCE_DIR}" OUTPUT_VARIABLE rel)

  string(APPEND ENUM "    ${symbol},\n")
  string(APPEND TABLE "    [${symbol}] = \"${rel}\",\n")
endforeach()

string(APPEND ENUM "\n    MESH_COUNT,\n};\n\n")
string(APPEND TABLE "};\n")

set(MANIFEST "${ENUM}${TABLE}")

set(OUT "${CMAKE_BINARY_DIR}/mesh_manifest.h")
if(EXISTS "${OUT}")
  file(READ "${OUT}" OLD)
else()
  set(OLD "")
endif()

if(NOT MANIFEST STREQUAL OLD)
  file(WRITE "${OUT}" "${MANIFEST}")
endif()

# Re-run CMake configure if any .glb file changes
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${MESH_FILES}")
